/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as EnlaceEnAccionRouteImport } from './routes/enlace-en-accion'
import { Route as EnfoqueRouteImport } from './routes/enfoque'
import { Route as EcosistemasRouteImport } from './routes/ecosistemas'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const EnlaceEnAccionRoute = EnlaceEnAccionRouteImport.update({
  id: '/enlace-en-accion',
  path: '/enlace-en-accion',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfoqueRoute = EnfoqueRouteImport.update({
  id: '/enfoque',
  path: '/enfoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosistemasRoute = EcosistemasRouteImport.update({
  id: '/ecosistemas',
  path: '/ecosistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/ecosistemas': typeof EcosistemasRoute
  '/enfoque': typeof EnfoqueRoute
  '/enlace-en-accion': typeof EnlaceEnAccionRoute
  '/metodologia': typeof MetodologiaRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/ecosistemas': typeof EcosistemasRoute
  '/enfoque': typeof EnfoqueRoute
  '/enlace-en-accion': typeof EnlaceEnAccionRoute
  '/metodologia': typeof MetodologiaRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/ecosistemas': typeof EcosistemasRoute
  '/enfoque': typeof EnfoqueRoute
  '/enlace-en-accion': typeof EnlaceEnAccionRoute
  '/metodologia': typeof MetodologiaRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/ecosistemas'
    | '/enfoque'
    | '/enlace-en-accion'
    | '/metodologia'
    | '/servicios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/ecosistemas'
    | '/enfoque'
    | '/enlace-en-accion'
    | '/metodologia'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/ecosistemas'
    | '/enfoque'
    | '/enlace-en-accion'
    | '/metodologia'
    | '/servicios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  EcosistemasRoute: typeof EcosistemasRoute
  EnfoqueRoute: typeof EnfoqueRoute
  EnlaceEnAccionRoute: typeof EnlaceEnAccionRoute
  MetodologiaRoute: typeof MetodologiaRoute
  ServiciosRoute: typeof ServiciosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enlace-en-accion': {
      id: '/enlace-en-accion'
      path: '/enlace-en-accion'
      fullPath: '/enlace-en-accion'
      preLoaderRoute: typeof EnlaceEnAccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfoque': {
      id: '/enfoque'
      path: '/enfoque'
      fullPath: '/enfoque'
      preLoaderRoute: typeof EnfoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosistemas': {
      id: '/ecosistemas'
      path: '/ecosistemas'
      fullPath: '/ecosistemas'
      preLoaderRoute: typeof EcosistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  EcosistemasRoute: EcosistemasRoute,
  EnfoqueRoute: EnfoqueRoute,
  EnlaceEnAccionRoute: EnlaceEnAccionRoute,
  MetodologiaRoute: MetodologiaRoute,
  ServiciosRoute: ServiciosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
